### PR TITLE
Remove forced lower case on all fields

### PR DESCRIPTION
**Pull request by jakedaleweb**

### CODE REVIEW

**Comment by dhensby** [comment]
This isn't configurable as per the referenced issue - do we want to drop that idea?

Perhaps it should be an option on the redirect rule itself?

**Comment by jakedaleweb** [comment]
@dhensby 
> This isn't configurable as per the referenced issue - do we want to drop that idea?
Yeah, speaking with Damian we thought better to be forgiving on the input and ensure a case insensitive comparison later on.

> Perhaps it should be an option on the redirect rule itself?
Same reason as above

> Can we get a test too, please?
Sure (:

**Comment by dhensby** [comment]
> ensure a case insensitive comparison later on

OK - What about being forgiving when comparing the keys, though? At the moment we are only forgiving on the value...

**Comment by thats4shaw** [comment]
Just into this issue myself.  Is it just a test remaining to get this merged in?

**Comment by robbieaverill** [comment]
I think this has been superseded by #50, feel free to reopen if that's not the case =)

**Pull request closed without merging**
